# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-01 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('tee_public', 'TeePublic'), ('tee_spring', 'TeeSpring'), ('red_buble', 'RedBuble')], default='amazon', max_length=255),
        ),
    ]
