# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170403_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]