# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170412_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]