# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-17 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='order',
            new_name='sort',
        ),
    ]