# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='keywords',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]