# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 13:12
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_export_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]